# Generated by Django 5.2.6 on 2026-06-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantproduct',
            name='image',
            field=models.ImageField(blank=True, help_text='Это поле меняется только в админке. Импорт из Excel его не затрагивает.', null=True, upload_to='products/%Y/%m/%d', verbose_name='Загруженная картинка'),
        ),
        migrations.AlterField(
            model_name='plantproduct',
            name='image_path',
            field=models.CharField(blank=True, default='', help_text='Резервный путь к изображению в static. Используется только если отдельная картинка не загружена.', max_length=255, verbose_name='Путь к изображению'),
        ),
    ]
