# Generated by Django 5.2.6 on 2026-06-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_split_existing_sort_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='advantage_1_text',
            field=models.TextField(default='Растения без лишней нагрузки и с предсказуемым стартом.', verbose_name='Преимущество 1 текст'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='advantage_1_title',
            field=models.CharField(default='Чистый посадочный материал', max_length=160, verbose_name='Преимущество 1 заголовок'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='advantage_2_text',
            field=models.TextField(default='Удобно высаживать и быстро формировать композиции.', verbose_name='Преимущество 2 текст'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='advantage_2_title',
            field=models.CharField(default='Компактная форма', max_length=160, verbose_name='Преимущество 2 заголовок'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='advantage_3_text',
            field=models.TextField(default='Хорошо смотрится в природных и дизайнерских аквариумах.', verbose_name='Преимущество 3 текст'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='advantage_3_title',
            field=models.CharField(default='Подходит для акваскейпа', max_length=160, verbose_name='Преимущество 3 заголовок'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='advantage_4_text',
            field=models.TextField(default='Помогаем с подбором и доставкой растений.', verbose_name='Преимущество 4 текст'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='advantage_4_title',
            field=models.CharField(default='Работаем по Москве', max_length=160, verbose_name='Преимущество 4 заголовок'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='order_step_1_text',
            field=models.TextField(default='Соберите список растений, которые нужны для вашего аквариума.', verbose_name='Этап заказа 1 текст'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='order_step_1_title',
            field=models.CharField(default='Выберите растения', max_length=160, verbose_name='Этап заказа 1 заголовок'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='order_step_2_text',
            field=models.TextField(default='Мы подтвердим актуальное наличие и подскажем варианты.', verbose_name='Этап заказа 2 текст'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='order_step_2_title',
            field=models.CharField(default='Согласуйте наличие', max_length=160, verbose_name='Этап заказа 2 заголовок'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='order_step_3_text',
            field=models.TextField(default='Напишите удобным способом и подтвердите состав заказа.', verbose_name='Этап заказа 3 текст'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='order_step_3_title',
            field=models.CharField(default='Оформите заказ', max_length=160, verbose_name='Этап заказа 3 заголовок'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='order_step_4_text',
            field=models.TextField(default='Заберите растения и высадите их в аквариум.', verbose_name='Этап заказа 4 текст'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='order_step_4_title',
            field=models.CharField(default='Получите и посадите', max_length=160, verbose_name='Этап заказа 4 заголовок'),
        ),
    ]
