# Generated by Django 5.2.6 on 2026-06-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_siteconfiguration_advantage_1_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='image_path',
            field=models.CharField(max_length=255, verbose_name='Путь к изображению'),
        ),
        migrations.AlterField(
            model_name='plantproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d', verbose_name='Загруженная картинка'),
        ),
        migrations.AlterField(
            model_name='plantproduct',
            name='image_path',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Путь к изображению'),
        ),
    ]
