# Generated by Django 5.2.6 on 2026-06-13 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_galleryitem_image_path_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantproduct',
            options={'ordering': ('variety_name', 'article'), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.RemoveField(
            model_name='plantproduct',
            name='display_order',
        ),
    ]
