# Generated by Django 5.2.6 on 2026-06-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_plantproduct_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlantProduct',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='price_catalog_title',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='price_notice',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='product_button_text',
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='site/gallery', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/sections', verbose_name='Изображение блока О нас'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/sections', verbose_name='Hero изображение'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/branding', verbose_name='Логотип сайта'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='plants_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/sections', verbose_name='Изображение блока Растения'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='plants_panel_text',
            field=models.CharField(default='Сайт стал чище: только тексты, визуалы и контакт для быстрого подбора растений.', max_length=255, verbose_name='Растения карточка текст'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='plants_panel_title',
            field=models.CharField(default='Контент вместо прайса', max_length=120, verbose_name='Растения карточка заголовок'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='plants_text',
            field=models.TextField(default='На сайте оставляем только контентную подачу: показываем стиль, качество и примеры работ, а актуальный подбор обсуждаем напрямую в сообщениях.', verbose_name='Растения описание'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='plants_eyebrow',
            field=models.CharField(default='Растения', max_length=120, verbose_name='Растения надзаголовок'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='plants_title',
            field=models.TextField(default='Подбор растений без публичного каталога и Excel', verbose_name='Растения заголовок'),
        ),
        migrations.DeleteModel(
            name='PriceUpload',
        ),
    ]
