# Generated by Django 5.2.6 on 2026-06-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_delete_plantproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='image_path',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Путь к изображению'),
        ),
    ]
