# Generated by Django 5.2.6 on 2026-06-13 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_galleryitem_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='advantage_1_text',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='advantage_1_title',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='advantage_2_text',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='advantage_2_title',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='advantage_3_text',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='advantage_3_title',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='advantage_4_text',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='advantage_4_title',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='order_step_1_text',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='order_step_1_title',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='order_step_2_text',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='order_step_2_title',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='order_step_3_text',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='order_step_3_title',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='order_step_4_text',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='order_step_4_title',
        ),
    ]
