# Generated by Django 5.2.6 on 2026-06-13 21:31

from django.db import migrations, models


def seed_faq_items(apps, schema_editor):
    faq_model = apps.get_model('catalog', 'FAQItem')
    if faq_model.objects.exists():
        return

    faq_model.objects.bulk_create(
        [
            faq_model(
                sort_order=1,
                question='\u041a\u0430\u043a \u0432\u044b\u0431\u0440\u0430\u0442\u044c \u043c\u0435\u0440\u0438\u0441\u0442\u0435\u043c\u043d\u044b\u0435 \u0430\u043a\u0432\u0430\u0440\u0438\u0443\u043c\u043d\u044b\u0435 \u0440\u0430\u0441\u0442\u0435\u043d\u0438\u044f \u0434\u043b\u044f \u043d\u043e\u0432\u043e\u0433\u043e \u0430\u043a\u0432\u0430\u0440\u0438\u0443\u043c\u0430?',
                answer='\u041e\u0440\u0438\u0435\u043d\u0442\u0438\u0440\u0443\u0439\u0442\u0435\u0441\u044c \u043d\u0430 \u043e\u0431\u044a\u0435\u043c \u0430\u043a\u0432\u0430\u0440\u0438\u0443\u043c\u0430, \u043c\u043e\u0449\u043d\u043e\u0441\u0442\u044c \u0441\u0432\u0435\u0442\u0430, \u043d\u0430\u043b\u0438\u0447\u0438\u0435 CO2 \u0438 \u0436\u0435\u043b\u0430\u0435\u043c\u0443\u044e \u043a\u043e\u043c\u043f\u043e\u0437\u0438\u0446\u0438\u044e. \u0414\u043b\u044f \u0441\u0442\u0430\u0440\u0442\u0430 \u0447\u0430\u0449\u0435 \u0432\u0441\u0435\u0433\u043e \u043f\u043e\u0434\u0445\u043e\u0434\u044f\u0442 \u043d\u0435\u043f\u0440\u0438\u0445\u043e\u0442\u043b\u0438\u0432\u044b\u0435 \u043f\u043e\u0447\u0432\u043e\u043f\u043e\u043a\u0440\u043e\u0432\u043d\u044b\u0435, \u0440\u043e\u0437\u0435\u0442\u043e\u0447\u043d\u044b\u0435 \u0438 \u0441\u0442\u0435\u0431\u0435\u043b\u044c\u043d\u044b\u0435 \u0432\u0438\u0434\u044b.',
            ),
            faq_model(
                sort_order=2,
                question='\u0427\u0435\u043c \u0440\u0430\u0441\u0442\u0435\u043d\u0438\u044f in vitro \u043e\u0442\u043b\u0438\u0447\u0430\u044e\u0442\u0441\u044f \u043e\u0442 \u043e\u0431\u044b\u0447\u043d\u044b\u0445 \u0430\u043a\u0432\u0430\u0440\u0438\u0443\u043c\u043d\u044b\u0445 \u0440\u0430\u0441\u0442\u0435\u043d\u0438\u0439?',
                answer='\u041c\u0435\u0440\u0438\u0441\u0442\u0435\u043c\u043d\u044b\u0435 \u0440\u0430\u0441\u0442\u0435\u043d\u0438\u044f \u0432\u044b\u0440\u0430\u0449\u0438\u0432\u0430\u044e\u0442\u0441\u044f \u0432 \u0441\u0442\u0435\u0440\u0438\u043b\u044c\u043d\u043e\u0439 \u0441\u0440\u0435\u0434\u0435, \u043f\u043e\u044d\u0442\u043e\u043c\u0443 \u0432 \u0431\u0430\u043d\u043e\u0447\u043a\u0435 \u043d\u0435\u0442 \u0443\u043b\u0438\u0442\u043e\u043a, \u0432\u043e\u0434\u043e\u0440\u043e\u0441\u043b\u0435\u0439 \u0438 \u043d\u0435\u0436\u0435\u043b\u0430\u0442\u0435\u043b\u044c\u043d\u044b\u0445 \u043f\u0440\u0438\u043c\u0435\u0441\u0435\u0439. \u042d\u0442\u043e \u0443\u0434\u043e\u0431\u043d\u043e \u0434\u043b\u044f \u0447\u0438\u0441\u0442\u043e\u0433\u043e \u0441\u0442\u0430\u0440\u0442\u0430 \u0438 \u0430\u043a\u043a\u0443\u0440\u0430\u0442\u043d\u043e\u0439 \u043f\u043e\u0441\u0430\u0434\u043a\u0438.',
            ),
            faq_model(
                sort_order=3,
                question='\u041c\u043e\u0436\u043d\u043e \u043b\u0438 \u0432\u044b\u0441\u0430\u0436\u0438\u0432\u0430\u0442\u044c \u043c\u0435\u0440\u0438\u0441\u0442\u0435\u043c\u043d\u044b\u0435 \u0440\u0430\u0441\u0442\u0435\u043d\u0438\u044f \u0431\u0435\u0437 CO2?',
                answer='\u0414\u0430, \u0447\u0430\u0441\u0442\u044c \u0432\u0438\u0434\u043e\u0432 \u0440\u0430\u0441\u0442\u0435\u0442 \u0438 \u0431\u0435\u0437 \u0434\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0439 \u043f\u043e\u0434\u0430\u0447\u0438 CO2, \u0435\u0441\u043b\u0438 \u0435\u0441\u0442\u044c \u0441\u0442\u0430\u0431\u0438\u043b\u044c\u043d\u044b\u0439 \u0441\u0432\u0435\u0442, \u043f\u0438\u0442\u0430\u043d\u0438\u0435 \u0438 \u0443\u0445\u043e\u0434. \u0414\u043b\u044f \u0441\u043b\u043e\u0436\u043d\u044b\u0445 \u043a\u043e\u043c\u043f\u043e\u0437\u0438\u0446\u0438\u0439 \u0438 \u0431\u044b\u0441\u0442\u0440\u043e\u0433\u043e \u043f\u043e\u043a\u0440\u043e\u0432\u0430 CO2 \u0434\u0430\u0435\u0442 \u0431\u043e\u043b\u0435\u0435 \u043f\u0440\u043e\u0433\u043d\u043e\u0437\u0438\u0440\u0443\u0435\u043c\u044b\u0439 \u0440\u0435\u0437\u0443\u043b\u044c\u0442\u0430\u0442.',
            ),
            faq_model(
                sort_order=4,
                question='\u041a\u0430\u043a \u0443\u0442\u043e\u0447\u043d\u0438\u0442\u044c \u043d\u0430\u043b\u0438\u0447\u0438\u0435 \u0440\u0430\u0441\u0442\u0435\u043d\u0438\u0439 Aquaklon \u0432 \u041c\u043e\u0441\u043a\u0432\u0435?',
                answer='\u0421\u0430\u043c\u044b\u0439 \u0431\u044b\u0441\u0442\u0440\u044b\u0439 \u0441\u043f\u043e\u0441\u043e\u0431 \u2014 \u043d\u0430\u043f\u0438\u0441\u0430\u0442\u044c \u0438\u043b\u0438 \u043f\u043e\u0437\u0432\u043e\u043d\u0438\u0442\u044c \u043f\u043e \u043a\u043e\u043d\u0442\u0430\u043a\u0442\u0430\u043c \u043d\u0430 \u0441\u0430\u0439\u0442\u0435. \u0422\u0430\u043a \u043c\u043e\u0436\u043d\u043e \u0441\u0440\u0430\u0437\u0443 \u043f\u0440\u043e\u0432\u0435\u0440\u0438\u0442\u044c \u0430\u043a\u0442\u0443\u0430\u043b\u044c\u043d\u043e\u0435 \u043d\u0430\u043b\u0438\u0447\u0438\u0435 \u0438 \u043f\u043e\u0434\u043e\u0431\u0440\u0430\u0442\u044c \u0440\u0430\u0441\u0442\u0435\u043d\u0438\u044f \u043f\u043e\u0434 \u0432\u0430\u0448 \u0430\u043a\u0432\u0430\u0440\u0438\u0443\u043c.',
            ),
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_siteconfiguration_advantage_1_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
            ],
            options={
                'verbose_name': 'FAQ item',
                'verbose_name_plural': 'FAQ items',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='google_site_verification',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Google site verification'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='meta_robots',
            field=models.CharField(default='index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1', max_length=160, verbose_name='Robots directives'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='seo_keywords',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='SEO keywords'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='social_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/seo', verbose_name='Social image'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='social_image_alt',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Social image alt'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='yandex_verification',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Yandex verification'),
        ),
        migrations.RunPython(seed_faq_items, migrations.RunPython.noop),
    ]
