# Generated by Django 5.2.6 on 2026-06-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_faqitem_siteconfiguration_google_site_verification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="contacts_telegram_button_text",
            field=models.CharField(default="Написать в Telegram", max_length=80, verbose_name="Кнопка Telegram"),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="telegram_url",
            field=models.URLField(blank=True, default="https://t.me/microklon", verbose_name="Ссылка Telegram"),
        ),
    ]
