# Generated by Django 5.2.6 on 2026-06-14 06:39

from pathlib import Path

from django.conf import settings
import catalog.models
from django.db import migrations, models


def seed_existing_price_file(apps, schema_editor):
    site_configuration = apps.get_model("catalog", "SiteConfiguration")
    config, _created = site_configuration.objects.get_or_create(pk=1)
    if config.price_file:
        return

    source = settings.BASE_DIR / "static" / "files" / "22.08.06.2026.xlsx"
    if not source.exists():
        return

    destination_relative = Path("site/prices/price-list.xlsx")
    destination = settings.MEDIA_ROOT / destination_relative
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_bytes(source.read_bytes())

    config.price_file = destination_relative.as_posix()
    config.price_file_original_name = source.name
    config.save(update_fields=("price_file", "price_file_original_name"))


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_siteconfiguration_telegram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='price_file',
            field=models.FileField(blank=True, null=True, storage=catalog.models.OverwriteStorage(), upload_to=catalog.models.upload_price_file, verbose_name='Файл с ценами'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='price_file_original_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Имя файла с ценами'),
        ),
        migrations.RunPython(seed_existing_price_file, migrations.RunPython.noop),
    ]
