# Generated by Django 5.2.6 on 2026-06-14 06:58

from django.db import migrations, models


def restore_plants_catalog_text(apps, schema_editor):
    SiteConfiguration = apps.get_model('catalog', 'SiteConfiguration')
    SiteConfiguration.objects.update_or_create(
        pk=1,
        defaults={
            'plants_eyebrow': 'Каталог растений',
            'plants_title': 'Популярные виды для аквариума и акваскейпа',
            'plants_text': 'Наличие и стоимость зависят от текущей партии. Напишите или позвоните, чтобы подобрать растения под освещение, объём и стиль композиции.',
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_siteconfiguration_price_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='plants_eyebrow',
            field=models.CharField(default='Каталог растений', max_length=120, verbose_name='Растения надзаголовок'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='plants_text',
            field=models.TextField(default='Наличие и стоимость зависят от текущей партии. Напишите или позвоните, чтобы подобрать растения под освещение, объём и стиль композиции.', verbose_name='Растения описание'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='plants_title',
            field=models.TextField(default='Популярные виды для аквариума и акваскейпа', verbose_name='Растения заголовок'),
        ),
        migrations.RunPython(restore_plants_catalog_text, migrations.RunPython.noop),
    ]
