# Generated by Django 5.2.6 on 2026-06-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_delete_faqitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='icon',
            field=models.CharField(choices=[('shield', 'Щит'), ('cup', 'Контейнер'), ('tweezers', 'Пинцет'), ('sprout', 'Росток'), ('grid', 'Сетка'), ('scape', 'Акваскейп'), ('leaf', 'Лист'), ('drop', 'Капля'), ('sun', 'Свет'), ('star', 'Звезда'), ('layers', 'Слои'), ('heart', 'Сердце'), ('spark', 'Искра'), ('waves', 'Волны')], default='shield', max_length=32, verbose_name='Иконка'),
        ),
    ]
