# Generated by Django 5.2.6 on 2026-06-14 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_benefit_icon_alter_galleryitem_image_alt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='canonical_url',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='google_site_verification',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='seo_keywords',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='yandex_verification',
        ),
    ]
