# Generated by Django 5.2.6 on 2026-06-14 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_remove_siteconfiguration_canonical_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='plants_text',
        ),
    ]
