# Generated by Django 5.2.6 on 2026-06-14 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_remove_siteconfiguration_plants_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='about_image',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='plants_image',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='plants_panel_text',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='plants_panel_title',
        ),
    ]
