# Generated by Django 5.2.6 on 2026-06-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_siteconfiguration_delivery_terms_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='image_alt',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Альтернативный текст'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='contact_email',
            field=models.EmailField(default='Aquaklon@yandex.ru', max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_eyebrow',
            field=models.CharField(default='Работаем в г. Москва · культура in vitro · акваскейп', max_length=255, verbose_name='Первый экран: надзаголовок'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_feature_1',
            field=models.CharField(default='Меристемное выращивание', max_length=120, verbose_name='Первый экран: преимущество 1'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_feature_2',
            field=models.CharField(default='Чистая культура', max_length=120, verbose_name='Первый экран: преимущество 2'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_feature_3',
            field=models.CharField(default='Подходит для акваскейпа', max_length=120, verbose_name='Первый экран: преимущество 3'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_feature_4',
            field=models.CharField(default='Работаем в г. Москва', max_length=120, verbose_name='Первый экран: преимущество 4'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/sections', verbose_name='Изображение первого экрана'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_lead',
            field=models.TextField(default='Aquaklon выращивает качественные аквариумные растения для акваскейпа, домашних и профессиональных аквариумов.', verbose_name='Первый экран: описание'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_primary_button_text',
            field=models.CharField(default='Узнать наличие', max_length=80, verbose_name='Первый экран: кнопка 1'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_secondary_button_text',
            field=models.CharField(default='Посмотреть растения', max_length=80, verbose_name='Первый экран: кнопка 2'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_title',
            field=models.TextField(default='Меристемные аквариумные растения для красивого и здорового аквариума', verbose_name='Первый экран: заголовок'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='meta_description',
            field=models.TextField(default='Меристемные аквариумные растения Aquaklon для акваскейпа, домашних и профессиональных аквариумов.', verbose_name='Мета-описание'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='meta_robots',
            field=models.CharField(default='index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1', max_length=160, verbose_name='Директивы robots'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='site_title',
            field=models.CharField(default='Aquaklon - меристемные аквариумные растения', max_length=255, verbose_name='Заголовок сайта'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='social_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/seo', verbose_name='Изображение для соцсетей'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='social_image_alt',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Описание изображения для соцсетей'),
        ),
    ]
