# Generated by SEO upgrade assistant
from django.db import migrations, models


def seed_faq_items(apps, schema_editor):
    FAQItem = apps.get_model("catalog", "FAQItem")
    defaults = [
        (
            "Чем меристемные растения отличаются от обычных аквариумных растений?",
            "Меристемные растения выращиваются в стерильной культуре in vitro. Такой формат помогает получить чистый посадочный материал без улиток, водорослей и случайных примесей.",
        ),
        (
            "Подходят ли растения Aquaklon для первого запуска аквариума?",
            "Да, меристемные растения удобны для первого запуска, акваскейпа и плотной посадки. Перед посадкой достаточно смыть питательный гель и разделить куст на небольшие пучки.",
        ),
        (
            "Можно ли уточнить наличие и актуальные цены перед заказом?",
            "Да, актуальное наличие и прайс можно уточнить по телефону, почте или в мессенджерах. На сайте также есть ссылка на файл с ценами.",
        ),
        (
            "Есть ли доставка по Москве и регионам?",
            "Условия заказа и доставки лучше уточнять перед оформлением: растения живые, поэтому способ отправки зависит от сезона, погоды и выбранного ассортимента.",
        ),
    ]
    for sort_order, (question, answer) in enumerate(defaults, start=10):
        FAQItem.objects.get_or_create(
            question=question,
            defaults={
                "answer": answer,
                "sort_order": sort_order,
                "is_published": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0020_alter_galleryitem_image_alt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="seo_keywords",
            field=models.CharField(
                blank=True,
                default="меристемные аквариумные растения, аквариумные растения in vitro, растения для акваскейпа, купить аквариумные растения, Aquaklon",
                max_length=500,
                verbose_name="SEO-ключевые фразы",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="google_site_verification",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Только значение content из meta-тега google-site-verification.",
                max_length=255,
                verbose_name="Google Search Console verification",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="yandex_site_verification",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Только значение content из meta-тега yandex-verification.",
                max_length=255,
                verbose_name="Яндекс.Вебмастер verification",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="contact_region",
            field=models.CharField(
                default="Москва и Московская область",
                max_length=160,
                verbose_name="Регион обслуживания",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="address_street",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="Адрес / ориентир"),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="opening_hours",
            field=models.CharField(
                default="Ежедневно, по предварительной договоренности",
                max_length=255,
                verbose_name="Режим работы",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="business_price_range",
            field=models.CharField(default="$$", max_length=32, verbose_name="Ценовой диапазон для schema.org"),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="nav_faq_label",
            field=models.CharField(default="FAQ", max_length=80, verbose_name="Пункт меню FAQ"),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="plants_text",
            field=models.TextField(
                default="В каталоге Aquaklon собраны меристемные аквариумные растения для переднего, среднего и заднего плана, запуска травника и оформления акваскейпа.",
                verbose_name="Растения SEO-описание",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="faq_eyebrow",
            field=models.CharField(default="Вопросы и ответы", max_length=120, verbose_name="FAQ надзаголовок"),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="faq_title",
            field=models.TextField(
                default="Что важно знать перед заказом меристемных растений",
                verbose_name="FAQ заголовок",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="faq_text",
            field=models.TextField(
                default="Собрали ответы на частые вопросы о формате in vitro, посадке, доставке и выборе растений для аквариума.",
                verbose_name="FAQ описание",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="seo_text_title",
            field=models.CharField(
                default="Меристемные аквариумные растения Aquaklon",
                max_length=255,
                verbose_name="SEO-текст заголовок",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="seo_text",
            field=models.TextField(
                default="Aquaklon выращивает и поставляет меристемные аквариумные растения для акваскейпа, домашних травников и профессиональных запусков. Формат in vitro помогает получить чистый посадочный материал без водорослей, улиток и случайных примесей, а компактная упаковка удобна для транспортировки и аккуратной посадки.",
                verbose_name="SEO-текст на странице",
            ),
        ),
        migrations.CreateModel(
            name="FAQItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
                ("is_published", models.BooleanField(default=True, verbose_name="Показывать на сайте")),
                ("question", models.CharField(max_length=255, verbose_name="Вопрос")),
                ("answer", models.TextField(verbose_name="Ответ")),
            ],
            options={
                "verbose_name": "Вопрос и ответ",
                "verbose_name_plural": "FAQ: вопросы и ответы",
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.RunPython(seed_faq_items, migrations.RunPython.noop),
    ]
