# Generated by Django 5.2.6 on 2026-07-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_sync_logo_to_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Единая иконка для сайта, админки и адреса /favicon.ico.', null=True, upload_to='site/branding', verbose_name='Favicon'),
        ),
    ]
