# Generated by Django 5.2.6 on 2026-07-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_alter_siteconfiguration_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='social_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/seo', verbose_name='Превью для соцсетей'),
        ),
    ]
