# Generated by Django 5.2.6 on 2026-07-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_siteconfiguration_about_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantproduct',
            name='image_path',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Резервный путь к изображению'),
        ),
    ]
