# Generated by Django 5.2.6 on 2026-07-10 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_alter_plantproduct_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantproduct',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='plantproduct',
            name='image_position',
        ),
        migrations.RemoveField(
            model_name='plantproduct',
            name='image_width',
        ),
    ]
